### ISSUE TITLE
A and B theory

### ISSUE THREAD

**Issue by iainmuntz** [koenderinklab/ddmPilotCode#23]
Create markdown file with theory of fitting A and B in a new docs folder

**Comment by iainmuntz** [comment]
I made a .tex and .pdf describing how it can be done. Not sure on the best way to make this documentation more accessible.

**Comment by mwakok** [comment]
I have added the content of the `.tex` file to the documentation: https://koenderinklab.github.io/ddmPilotCode/theory.html 

I couldn't find a simple way to render the `.tex` file with sphinx. However, it is possible to write the equations in a markdown file with only minor syntax changes: https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#math-shortcuts
