### ISSUE TITLE
Data handling

### ISSUE THREAD

**Issue by mwakok** [koenderinklab/ddmPilotCode#9]

**Comment by iainmuntz** [comment]
Looking at nd2
Running pims.open('file.nd2') works for nd2 files and (presumably) .tif files although these are not tested
pims.open and nd2reader don't seem to find the frame rate, although they have other metadata such as pixels per micron
opening .lif file is proving tricky as it seems to rely on java things

**Comment by iainmuntz** [comment]
I have implemented .nd2 files and .lif file handling, converting them to dask arrays with the same formatting for future analysis.

A note on .lif files is that they are 4 dimensional, as well as the usual x, y, t you also have 'series' as a dimension which lets you save multiple experiments in one file. I have not yet implemented a workaround for handling this so for the moment the read_lif function just reads in the first series
